export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_ALL_PERSONNEL_START =  'GET_ALL_PERSONNEL_START';
export const GET_ALL_PERSONNEL_SUCCESS= 'GET_ALL_PERSONNEL_SUCCESS';
export const GET_ALL_PERSONNEL_FAIL =   'GET_ALL_PERSONNEL_FAIL';

export const GET_ALL_FACILITY_START =   'GET_ALL_FACILITY_START';
export const GET_ALL_FACILITY_SUCCESS = 'GET_ALL_FACILITY_SUCCESS';
export const GET_ALL_FACILITY_FAIL =    'GET_ALL_FACILITY_FAIL';

export const GET_ALL_PROVIDER_START =   'GET_ALL_PROVIDER_START';
export const GET_ALL_PROVIDER_SUCCESS = 'GET_ALL_PROVIDER_SUCCESS';
export const GET_ALL_PROVIDER_FAIL =    'GET_ALL_PROVIDER_FAIL';

